version: '3'
services:
  userapi:
    image: usersapi
    build: .
    ports:
      - "8881:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/test
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: my-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin


