version : "3"
services:
  userapi:
    image : userapi
    restart: always
    build : .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_PORT: 3307
  mysqldb:
    image: mysql
    restart: always
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin

